### ISSUE TITLE
History disappears

### ISSUE THREAD

**Issue by siriocra** [nicolas-ivanov/Rino#10]
I met such a problem: after calling someone with no phone number, this command is in history for a while, but then is disappears after a little while. Seems like other commands have no problems with it.

**Comment by nicolas-ivanov** [comment]
I don't know what's the matter, Ira.
On my phone such a command is just not added to the history list, and that's a proper behavior, according to the code.
Anyway, we should rewrite a big piece of code in CommandAnalyser to make the structure more clear, so probably this bug won't be topical in a while.

**Comment by siriocra** [comment]
Check that command is set in every type of command in CommandAnalyzer. Maybe result Intent command adding should be out of commands or not found clause. 
I also have a problem with changing from speaking to writing. At the very first written command it doesn't use keyboard(though it looks like keyboard is working) and I always have to submit an empty string. After first submit everything is back to normal.
