### ISSUE TITLE
Patterns in file

### ISSUE THREAD

**Issue by siriocra** [nicolas-ivanov/Rino#2]
Put patterns in file and a way to download them on phone

**Comment by siriocra** [comment]
Added an ability to load and use patterns from file

**Comment by siriocra** [comment]
The format of patterns file: <unique code for operation>#<pattern>#<a list of parameters in order they meet in pattern, separated by spaces>. This list shows which groups we choose from pattern, give them names and specify order in pattern. We can use it e.g. if pattern can be both <number> <name> and <name> <number>

**Comment by nicolas-ivanov** [comment]
Better patterns' pattern:
(\\d+)\\t(.+)\\t~\\t(.+)

group1 - pattern's id
group2 - command
group3 - parameters list

example: 
1   позвони (+?[\d\s]+) ~   number1

Tabs for extra readability, 
# is replaced with ~ to avoid confusions with # in commands (for example: "call *100#").

**Comment by nicolas-ivanov** [comment]
Even better patterns' pattern:

<pre>
(\\w+)\\t+([^\\t~]+)(\\t~\\t(.+))?
</pre>

Structure:
- group1 - pattern's id (a word instead of number, for ex. "call_num")
- then one or more tabs for better readability
- group2 - a command (anything except tabs and ~)
- group3 - optional parameters section
- group4 - parameters list

Example: 

<pre>
call_num        (\w*звон\w+) (\+?[\d\s]+)   ~   number1
</pre>

**Comment by siriocra** [comment]
Parameter section should not be optional(Or should?). We have groups in every pattern, and we should describe them

**Comment by siriocra** [comment]
We should change our patterns file format. We should create one file with key words and command code, find necessary command using finding substring, then create one file for every type of command and write specific commands with parameters in it. There also should be a file for ambiguously detected commands. Maybe we should think of changing structure to patterns we wrote in our course work last year. I don't think this structure is good enough. Another question is whether we are going to use simple patterns for numbers and other simple things in one more file.
