### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by siriocra** [nicolas-ivanov/Rino#6]
I had problems with importing the project into Eclipse, so I suggest to discuss it. The main problem is in the file project.properties. In fact, I don't have the full version of all devices, because it takes a lot of space. So I always have to low down this version. I think we should either exclude this file from repository for manual parameters or set a lower version (10 or 14 there voice recognition is presented). The second question is in the Manifest. Should we really write things like this: 
<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="17" />
I had no problems with installing the app on my phone(though I have version 10), but is it ok to use such high target version?

**Comment by nicolas-ivanov** [comment]
Ok, Ira, I'll take a look at it now.

**Comment by nicolas-ivanov** [comment]
Problem 1:
1. The size of sdk-17 platform is 75 Mb, that's not so much :)
2. It seems to me it's a good idea not to exlude this file from repo, cause I've read in several places that it's an essential part of the project. For instance: http://developer.android.com/tools/projects/index.html
3. The target version parameter should not be lowered. Instead our app would not look native on devices with higher android version and we wouldn't be able to use new features, that's not cool.
So, as for me, the right decision is to install sdk-17 platform.

**Comment by siriocra** [comment]
I agree with you, I'll just use another version. I'll exclude this file from repo.

**Comment by nicolas-ivanov** [comment]
Ira, why to exclude it? Look item 2 in my answer :)

**Comment by nicolas-ivanov** [comment]
Problem 2:
Yes, it's absolutely ok to write
< uses-sdk android:minSdkVersion="8" android:targetSdkVersion="17" / >
This line is not essential in manifest, but it's better to keep it, since it prevents our program to be run on inappropriate version of android, for instance if we use in our app a method, that was not realised in previous android versions.

**Comment by siriocra** [comment]
We don't need to store this file at all. Build information is not stored in repos, because different people(like you and me, for example) may use different build properties and versions. It is not a library, it is a file that shows what version you'd like to use and it may change. Eclipse will automatically create this file in project.
It is build-specific thing.

**Comment by nicolas-ivanov** [comment]
Ok.
