### ISSUE TITLE
"PIck up a contact" feature

### ISSUE THREAD

**Issue by nicolas-ivanov** [nicolas-ivanov/Rino#9]
Realize a feature, that allows to pick up a contact proceeding from people names.

Subtasks:
- [ ] detect names and aliases in the input sequence
- [ ] get a person's contact from the contact book proceding from his name or alias
- [ ] pass obtained contact to an application that requires it

Examples:

> позвони маме
> напиши письмо Коле
> отправить Ире смску
> набери Василия Ивановича

**Comment by siriocra** [comment]
Realized a simple version comparison symbol by symbol

**Comment by nicolas-ivanov** [comment]
Program crashes, if there is a contact without a phone number...

**Comment by siriocra** [comment]
Strange, it is alright with my phone. Bug not reproducible.

**Comment by nicolas-ivanov** [comment]
Looks like the problem is not actually connected to contacts without phone numbers.
Instead, it probably has concern with '.toLowerCase(Locale.getDefault())' function in ContactsDatabase class.
If I remove it and pass just a 'name' without applying this function, then the retrieving works ok, otherwise I get a NullPointerException on the last contact:

<pre>
03-14 22:12:50.623: E/AndroidRuntime(28825): Caused by: java.lang.NullPointerException
03-14 22:12:50.623: E/AndroidRuntime(28825):    at com.example.rino.ContactsDatabase.addContact(ContactsDatabase.java:23)
03-14 22:12:50.623: E/AndroidRuntime(28825):    at com.example.rino.MainActivity.retrieveContacts(MainActivity.java:62)
03-14 22:12:50.623: E/AndroidRuntime(28825):    at com.example.rino.MainActivity.onCreate(MainActivity.java:90)
</pre>

Another interesting fact: if query with sort order 

<pre>
.query(ContactsContract.Contacts.CONTENT_URI, null, null, null, PhoneLookup.DISPLAY_NAME);
</pre>

then again the problem disappears...

**Comment by siriocra** [comment]
Another question is how to find contact names. A suggestion is to use ready vocabulary for russian names with all forms, then use finding minimal distance.

**Comment by nicolas-ivanov** [comment]
Yes, using a vocabulary is a good option, but I'm not sure that we need all name forms in it...
Probably, it's enough to store 2 or 3 different stems, for example:

formal name, informal name, nickname

<pre>
алексе, леш, лех
артем, тем
владислав, слав
михаил, миш, мих
анастас, наст, тас
</pre>

We don't really need endings here, since we compute a minimal distance and not exact correspondence. 
On the contrary, word roots are much more informative in this case.

**Comment by siriocra** [comment]
Realized only minimal distance without vocabulary. Strange bug with getting first and last names: not all of existing found

**Comment by nicolas-ivanov** [comment]
A consideration about the way phone contacts should be dealt with:

There should be a custom data base that hosts a limited number of most frequently used contacts.
This db needs only three fields: 
- id – row id
- contactName – a string, representing a real name or nickname, that the person will be likely searched with
- contactID – a contact id, that will be used to query this contact in global contacts db to retrieve any data needed

Note, by storing this little, we get rid of updating our db, except the cases, when a contact is deleted from the global contacts db or it's name is changed.

First any person's name should be looked in our custom db by applying current
ContactsDatabase.getContacts(String contactName) function.
Thus we get a very quick search in most cases, computing ContactsDatabase.findMinDist(String s1, String s2) function only for a limited number of frequently used contacts.

If this search fails, then the global db is searched.
If the conctact is found in it, the corresponding row with 'contactID' and 'contactName' fields should be added to our db (replacing an old contact, if needed).
'contactName' should be equal to a string, that we got after recognition process, no matter what it is, because next time it will be likely recognized the same way.

Probably, it makes sense to limit our db with 30-50 rows to keep high speed of search process.

The custom db should be implemented as SQLite:
http://startandroid.ru/ru/uroki/vse-uroki-spiskom/74-urok-34-hranenie-dannyh-sqlite.html
